console.log(document.documentElement.lang)
console.log(document.documentElement.getAttribute('lang'))
console.log(document.querySelector('nav-sesion').href)
console.log(document.querySelector('nav-sesion').getAttribute('href'))
const $navsesion = document.querySelector(',nav-sesion')
$navsesion.setAttribute("target", "_blanck")
console.log($navsesion.hasAttribute("href"))
$navsesion.removeAttribute(href)
console.log($navsesion.hasAttribute('href'))
const $titulo = document.querySelector(".titulo")